from pathlib import Path
import json

root=Path('app')
def read(p): return (root/p).read_text(encoding='utf-8')
def write(p,s): (root/p).write_text(s,encoding='utf-8')
def must(s,a,b,label):
    if a not in s: raise RuntimeError(f'Trecho não encontrado: {label}')
    return s.replace(a,b,1)

pkg=json.loads(read('package.json'));pkg['version']='10.4.0';write('package.json',json.dumps(pkg,indent=2,ensure_ascii=False))

s=read('src/server.ts')
s=must(s,
'''type Cliente = {\n  lojaId:number;\n  id:number; nome:string; cpf:string; telefone:string; email:string;\n  ativo:boolean; criadoEm:string; atualizadoEm:string;\n};''',
'''type Cliente = {\n  lojaId:number;\n  id:number; nome:string; cpf:string; telefone:string; email:string;\n  cep:string; endereco:string; numero:string; complemento:string; bairro:string; cidade:string; uf:string;\n  ativo:boolean; criadoEm:string; atualizadoEm:string;\n};''','tipo Cliente')
s=must(s,
'''  id:number; clienteId:number|null; clienteNome:string;\n  compradorDocumento:string; compradorTelefone:string; compradorEmail:string;''',
'''  id:number; clienteId:number|null; clienteNome:string;\n  compradorDocumento:string; compradorTelefone:string; compradorEmail:string; compradorEndereco?:string;''','endereco na Venda')
s=must(s,
'''  const lojaId=lojaIdReq(req);const c:Cliente={lojaId,id:db.seq.cliente++,nome,cpf,telefone:String(req.body.telefone||""),email:String(req.body.email||""),ativo:true,criadoEm:now(),atualizadoEm:now()};''',
'''  const lojaId=lojaIdReq(req);const c:Cliente={lojaId,id:db.seq.cliente++,nome,cpf,telefone:String(req.body.telefone||""),email:String(req.body.email||""),cep:String(req.body.cep||""),endereco:String(req.body.endereco||""),numero:String(req.body.numero||""),complemento:String(req.body.complemento||""),bairro:String(req.body.bairro||""),cidade:String(req.body.cidade||""),uf:String(req.body.uf||"").toUpperCase(),ativo:true,criadoEm:now(),atualizadoEm:now()};''','cadastro Cliente')
s=must(s,
'''  c.nome=String(req.body.nome??c.nome);c.cpf=cpf;c.telefone=String(req.body.telefone??c.telefone);c.email=String(req.body.email??c.email);c.ativo=req.body.ativo===undefined?c.ativo:Boolean(req.body.ativo);c.atualizadoEm=now();''',
'''  c.nome=String(req.body.nome??c.nome);c.cpf=cpf;c.telefone=String(req.body.telefone??c.telefone);c.email=String(req.body.email??c.email);c.cep=String(req.body.cep??c.cep??"");c.endereco=String(req.body.endereco??c.endereco??"");c.numero=String(req.body.numero??c.numero??"");c.complemento=String(req.body.complemento??c.complemento??"");c.bairro=String(req.body.bairro??c.bairro??"");c.cidade=String(req.body.cidade??c.cidade??"");c.uf=String(req.body.uf??c.uf??"").toUpperCase();c.ativo=req.body.ativo===undefined?c.ativo:Boolean(req.body.ativo);c.atualizadoEm=now();''','edicao Cliente')
s=must(s,
'''    const cliente=db.clientes.find(c=>c.lojaId===lojaId&&c.id===Number(clienteId));\n    const totalVenda=subtotal+adicional-d;''',
'''    const cliente=db.clientes.find(c=>c.lojaId===lojaId&&c.id===Number(clienteId));\n    const enderecoComprador=cliente?[cliente.endereco,cliente.numero,cliente.complemento,cliente.bairro,cliente.cidade,cliente.uf,cliente.cep?`CEP ${cliente.cep}`:``].filter(Boolean).join(", "):"";\n    const totalVenda=subtotal+adicional-d;''','endereco comprador')
s=must(s,
'''clienteNome:cliente?.nome||"Consumidor final",compradorDocumento:String(compradorDocumento||""),compradorTelefone:String(compradorTelefone||""),compradorEmail:String(compradorEmail||""),usuarioId:u.id''',
'''clienteNome:cliente?.nome||"Consumidor final",compradorDocumento:String(compradorDocumento||cliente?.cpf||""),compradorTelefone:String(compradorTelefone||cliente?.telefone||""),compradorEmail:String(compradorEmail||cliente?.email||""),compradorEndereco:enderecoComprador,usuarioId:u.id''','snapshot comprador')
s=must(s,
'''  v.status="cancelada";v.canceladoEm=now();salvar();res.json(v);\n});\n\n\n// Fiscal:''',
'''  v.status="cancelada";v.canceladoEm=now();salvar();res.json(v);\n});\napp.delete("/api/vendas/:id",auth,admin,(req,res)=>{\n  const lojaId=lojaIdReq(req),id=Number(req.params.id);\n  const idx=db.vendas.findIndex(v=>v.lojaId===lojaId&&v.id===id);\n  if(idx<0)return res.status(404).json({erro:"Venda não encontrada."});\n  if(db.vendas[idx].status!=="cancelada")return res.status(400).json({erro:"Só é possível excluir uma venda cancelada."});\n  db.vendas.splice(idx,1);\n  db.movimentos=db.movimentos.filter(m=>!(m.lojaId===lojaId&&(m.motivo===`Venda #${id}`||m.motivo===`Cancelamento da venda #${id}`)));\n  salvar();res.json({ok:true,id});\n});\n\n\n// Fiscal:''','excluir venda')
s=must(s,
'''    lucroEstimado,\n    estoqueBaixo:db.produtos.filter(p=>p.lojaId===lojaId&&p.ativo&&p.estoque<=p.estoqueMinimo).length,\n    pagamentos,''',
'''    lucroEstimado,\n    estoqueBaixo:db.produtos.filter(p=>p.lojaId===lojaId&&p.ativo&&p.estoque<=p.estoqueMinimo).length,\n    pendencias:{\n      produtosIncompletos:db.produtos.filter(p=>{if(p.lojaId!==lojaId||!p.ativo)return false;const marca=String(p.marca||"").trim().toLowerCase(),categoria=String(p.categoria||"").trim().toLowerCase();return !String(p.codigo||"").trim()||!String(p.nome||"").trim()||!marca||["não informada","nao informada","sem marca"].includes(marca)||!categoria||["importados","não informada","nao informada"].includes(categoria)||!(Number(p.precoVenda)>0)||!(Number(p.precoCusto)>0)}).length,\n      estoqueBaixo:db.produtos.filter(p=>p.lojaId===lojaId&&p.ativo&&p.estoque>0&&p.estoque<=p.estoqueMinimo).length,\n      semEstoque:db.produtos.filter(p=>p.lojaId===lojaId&&p.ativo&&p.estoque<=0).length,\n      vendasCanceladas:db.vendas.filter(v=>v.lojaId===lojaId&&v.status==="cancelada").length,\n      caixaAberto:db.caixas.some(c=>c.lojaId===lojaId&&c.status==="aberto")\n    },\n    pagamentos,''','dashboard pendencias')
write('src/server.ts',s)

js=read('public/app.js')
js=must(js,
'''function clienteForm(c={}){return `<form id="modalClientForm" class="form-grid"><div class="full"><label>Nome</label><input name="nome" value="${esc(c.nome||"")}" required></div>${c.id?`<div><label>Status</label><select name="ativo"><option value="true" ${c.ativo?"selected":""}>Ativo</option><option value="false" ${!c.ativo?"selected":""}>Inativo</option></select></div>`:""}<button class="primary full">${c.id?"Salvar alterações":"Cadastrar cliente"}</button></form>`}''',
'''function clienteForm(c={}){return `<form id="modalClientForm" class="form-grid"><div class="full"><label>Nome / Razão social</label><input name="nome" value="${esc(c.nome||"")}" required></div><div><label>CPF/CNPJ (opcional)</label><input name="cpf" value="${esc(c.cpf||"")}"></div><div><label>Telefone (opcional)</label><input name="telefone" value="${esc(c.telefone||"")}"></div><div class="full"><label>E-mail (opcional)</label><input name="email" type="email" value="${esc(c.email||"")}"></div><div><label>CEP (opcional)</label><input name="cep" value="${esc(c.cep||"")}"></div><div><label>Endereço (opcional)</label><input name="endereco" value="${esc(c.endereco||"")}" placeholder="Rua / Avenida"></div><div><label>Número</label><input name="numero" value="${esc(c.numero||"")}"></div><div><label>Complemento</label><input name="complemento" value="${esc(c.complemento||"")}"></div><div><label>Bairro</label><input name="bairro" value="${esc(c.bairro||"")}"></div><div><label>Cidade</label><input name="cidade" value="${esc(c.cidade||"")}"></div><div><label>UF</label><input name="uf" maxlength="2" value="${esc(c.uf||"")}" placeholder="SP"></div>${c.id?`<div><label>Status</label><select name="ativo"><option value="true" ${c.ativo?"selected":""}>Ativo</option><option value="false" ${!c.ativo?"selected":""}>Inativo</option></select></div>`:""}<button class="primary full">${c.id?"Salvar alterações":"Cadastrar cliente"}</button></form>`}''','form cliente')
js=must(js,
'''async function saveCliente(e,id=null){e.preventDefault();const raw=Object.fromEntries(new FormData(e.target));raw.cpf="";raw.telefone="";raw.email="";if(id)raw.ativo=raw.ativo==="true";const r=await api(id?`/api/clientes/${id}`:"/api/clientes",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(raw)}),d=await r.json();if(!r.ok)return toast(d.erro);closeModal();await loadClientes();toast(id?"Cliente atualizado.":"Cliente cadastrado.")}''',
'''async function saveCliente(e,id=null){e.preventDefault();const raw=Object.fromEntries(new FormData(e.target));if(id)raw.ativo=raw.ativo==="true";const r=await api(id?`/api/clientes/${id}`:"/api/clientes",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(raw)}),d=await r.json();if(!r.ok)return toast(d.erro);closeModal();await loadClientes();toast(id?"Cliente atualizado.":"Cliente cadastrado.")}''','salvar cliente')
js=must(js,
'''${v.compradorEmail?`<p>E-mail: ${esc(v.compradorEmail)}</p>`:""}<p>Vendedor:''',
'''${v.compradorEmail?`<p>E-mail: ${esc(v.compradorEmail)}</p>`:""}${v.compradorEndereco?`<p>Endereço: ${esc(v.compradorEndereco)}</p>`:""}<p>Vendedor:''','endereco comprovante')
js=must(js,
'''${me.cargo==="admin"&&v.status==="concluida"?`<button class="edit" onclick="fiscalVenda(${v.id})">Fiscal</button><button class="delete" onclick="cancelVenda(${v.id})">Cancelar</button>`:""}''',
'''${me.cargo==="admin"&&v.status==="concluida"?`<button class="edit" onclick="fiscalVenda(${v.id})">Fiscal</button><button class="delete" onclick="cancelVenda(${v.id})">Cancelar</button>`:""}${me.cargo==="admin"&&v.status==="cancelada"?`<button class="delete" onclick="deleteVenda(${v.id})">Excluir</button>`:""}''','botao excluir venda')
needle='''async function cancelVenda(id){if(!confirm(`Cancelar a venda #${id}? O estoque será devolvido.`))return;const r=await api(`/api/vendas/${id}/cancelar`,{method:"POST"}),d=await r.json();if(!r.ok)return toast(d.erro);await Promise.all([loadVendas(),loadProdutos(),loadDashboard()]);toast("Venda cancelada.")}'''
js=must(js,needle,needle+'''\nasync function deleteVenda(id){if(!confirm(`Excluir definitivamente a venda cancelada #${id}? Ela deixará de aparecer no histórico e nos relatórios.`))return;const r=await api(`/api/vendas/${id}`,{method:"DELETE"}),d=await r.json();if(!r.ok)return toast(d.erro||"Não foi possível excluir a venda.");await Promise.all([loadVendas(),loadDashboard()]);toast(`Venda #${id} excluída.`)}''','funcao excluir venda')
js=must(js,
'''async function loadDashboard(){const d=await(await api("/api/dashboard")).json();$("#dashVendas").textContent=d.vendasHoje;$("#dashFat").textContent=money(d.faturamento);$("#dashTicket").textContent=money(d.ticketMedio);$("#dashEstoque").textContent=d.estoqueBaixo;$("#pagamentosResumo").innerHTML=Object.entries(d.pagamentos).map(([k,v])=>`<div class="summary-row"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join("")||"<p class='muted'>Sem vendas hoje.</p>";$("#maisVendidos").innerHTML=d.maisVendidos.map((x,i)=>`<div class="summary-row"><span>${i+1}. ${esc(x.nome)}</span><b>${x.qtd} un.</b></div>`).join("")||"<p class='muted'>Sem vendas registradas.</p>"}''',
'''async function loadDashboard(){const d=await(await api("/api/dashboard")).json();$("#dashVendas").textContent=d.vendasHoje;$("#dashFat").textContent=money(d.faturamento);$("#dashTicket").textContent=money(d.ticketMedio);$("#dashEstoque").textContent=d.estoqueBaixo;$("#pagamentosResumo").innerHTML=Object.entries(d.pagamentos).map(([k,v])=>`<div class="summary-row"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join("")||"<p class='muted'>Sem vendas hoje.</p>";$("#maisVendidos").innerHTML=d.maisVendidos.map((x,i)=>`<div class="summary-row"><span>${i+1}. ${esc(x.nome)}</span><b>${x.qtd} un.</b></div>`).join("")||"<p class='muted'>Sem vendas registradas.</p>";const p=d.pendencias||{};const el=$("#dashboardPendencias");if(el)el.innerHTML=`<button class="pending-row" data-pending="incompletos"><span>Produtos faltando informação</span><b>${p.produtosIncompletos||0}</b></button><button class="pending-row" data-pending="baixo"><span>Estoque baixo</span><b>${p.estoqueBaixo||0}</b></button><button class="pending-row" data-pending="zerado"><span>Produtos sem estoque</span><b>${p.semEstoque||0}</b></button><button class="pending-row" data-pending="canceladas"><span>Vendas canceladas</span><b>${p.vendasCanceladas||0}</b></button><div class="pending-row static"><span>Caixa atual</span><b>${p.caixaAberto?"Aberto":"Fechado"}</b></div>`}''','dashboard')
js+='''\ndocument.addEventListener("click",e=>{const b=e.target?.closest?.("[data-pending]");if(!b)return;const tipo=b.dataset.pending;if(tipo==="incompletos"){document.querySelector('.nav[data-s="produtos"]')?.click();setTimeout(()=>{filtroProdutosIncompletos=true;renderProdutos()},80);return}if(tipo==="canceladas"){document.querySelector('.nav[data-s="vendas"]')?.click();return}if(tipo==="baixo"||tipo==="zerado"){document.querySelector('.nav[data-s="produtos"]')?.click();return}});\n'''
write('public/app.js',js)

h=read('public/index.html')
needle='''  <div class="two-cols">\n    <div class="card"><h3>Formas de pagamento hoje</h3><div id="pagamentosResumo"></div></div>\n    <div class="card"><h3>Produtos mais vendidos</h3><div id="maisVendidos"></div></div>\n  </div>'''
h=must(h,needle,needle+'''\n  <div class="card pending-card"><div class="pending-title"><div><h3>Pendências</h3><p class="muted">O que precisa da sua atenção agora.</p></div></div><div id="dashboardPendencias" class="pending-list"></div></div>''','dashboard html')
write('public/index.html',h)

css=read('public/style.css')
css+='''\n.pending-card{margin-top:14px}.pending-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.pending-title h3{margin:0}.pending-list{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}.pending-row{border:1px solid var(--border);background:var(--card-bg);border-radius:10px;padding:11px;display:flex;flex-direction:column;gap:5px;text-align:left;color:inherit;cursor:pointer}.pending-row.static{cursor:default}.pending-row span{font-size:11px;color:var(--muted)}.pending-row b{font-size:20px}.pending-row:hover:not(.static){border-color:var(--primary)}@media(max-width:900px){.pending-list{grid-template-columns:repeat(2,minmax(0,1fr))}}\n'''
write('public/style.css',css)
print('Patch 10.4.0 aplicado.')